vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|04 Aug 2005 21:21:46 -0000
vti_extenderversion:SR|5.0.2.6738
vti_backlinkinfo:VX|palm/Pedidos.ASP
vti_cacheddtm:TX|04 Aug 2005 21:21:46 -0000
vti_filesize:IR|5962
vti_cachedlinkinfo:VX|A|pedidos.asp
vti_cachedsvcrellinks:VX|FAUS|palm/pedidos.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_lineageid:SR|{74302D4C-D4F3-4439-BD3D-24E2C028B7BF}
